name: kubernetes-no-prometheus
description: Kubernetes stack when Prometheus namespace is not present

scrapes:
  - alloy-self
  - k8s-pod-logs-kubernetes
  - k8s-pod-metrics-kubernetes
  - k8s-node-metrics-filtered
  - k8s-node-exporter-custom
